# Generated by Django 6.0.3 on 2026-03-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_watchlist_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchhistory',
            name='current_time_seconds',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='watchhistory',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='watchhistory',
            name='total_duration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
