# Generated by Django 6.0.3 on 2026-03-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_watchhistory_current_time_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchhistory',
            name='episode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watchhistory',
            name='season',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
