# Generated by Django 6.1 on 2026-08-20 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_watchhistory_episode_watchhistory_season'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VIPSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('admin', '👑 VIP Supreme Admin Pass (Ultimate Access)'), ('annual', '⭐ VIP Annual Pass (1 Year Access)'), ('monthly', '🌙 VIP Monthly Pass (1 Month Access)')], default='annual', max_length=20)),
                ('invoice_no', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(default='PAID', max_length=20)),
                ('payment_gateway', models.CharField(default='Xendit Official Gateway', max_length=50)),
                ('amount_paid', models.CharField(default='$11.99 USD', max_length=50)),
                ('valid_until', models.CharField(default='Aug 20, 2027', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vip_subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'VIP Subscription & Invoice',
                'verbose_name_plural': 'VIP Subscriptions & Invoices',
                'ordering': ['-created_at'],
            },
        ),
    ]
