# Generated by Django 5.2.17 on 2026-08-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_vipsubscription_checkout_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vipsubscription',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
